### ISSUE TITLE
Addon Error message

### ISSUE THREAD

**Issue by Aneko1** [DungFu/LayerHopper#2]
Received this error in orgrimmar.

[LayerHopper] YOU HAVE ENCOUNTERED A MOB THAT BREAKS LAYER HOPPER! 
[LayerHopper] MOB NAME: Orcish Orphan 
[LayerHopper] MOB GUID: Creature-0-4412-409-2322-14444-00002E48D9 
[LayerHopper] ZONE: Valley of Strength, Orgrimmar 
[LayerHopper] PLEASE SEND THIS INFORMATION TO KUTANO (OR REPORT ON GITHUB)!

**Comment by DungFu** [comment]
thanks for reporting this! I have pushed out a new version that blacklists some of the mobs that have been reported :)
