### ISSUE TITLE
[Request] The precise jump

### ISSUE THREAD

**Issue by Sethox** [DungFu/LayerHopper#3]
Thanks for publicise this addon it helps a lot for the gameplay. Though one small request that should be able to do is to list the layers available (either by another addon to gain this functionality or your own implementation). The reason for this is the same exact reason you want to jump to another layer but not just randomly, specific layers.

Thanks again for this addon !

**Comment by DungFu** [comment]
Blizzard has stated that there will never be more than 2 layers on any Classic server. If you want to list what layers are known in your guild, you can use the "/lh list" command to see all the layers for guildies.
